name: Detect exposed secrets

on:
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Detect git fetch depth
        shell: bash
        env:
          EVENT_COMMITS: ${{ toJson(github.event.commits) }}
          REF_NAME: ${{ github.ref_name }}
          EVENT_PR_COMMITS: ${{ github.event.pull_request.commits }}
          EVENT_PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(($(jq length <<< $EVENT_COMMITS) + 2))" >> $GITHUB_ENV
            echo "branch=$REF_NAME" >> $GITHUB_ENV
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$(($EVENT_PR_COMMITS + 2))" >> $GITHUB_ENV
            echo "branch=$EVENT_PR_HEAD_REF" >> $GITHUB_ENV
          fi

      - name: Shallow git clone
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
          persist-credentials: false

      - name: Secrets scan
        uses: trufflesecurity/trufflehog@466da5b0bb161144f6afca9afe5d57975828c410 # v3.90.8
        with:
          version: 3.90.8
          extra_args: --results=verified

      - name: Notify through Slack
        if: always() && failure()
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SECRETS_SCANNER_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "Secrets detected in ${{ github.repository }}"
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    *Repository*: <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
                    *User*: ${{ github.actor }}
                    *Branch*: ${{ github.ref_name }}
              - type: section
                fields:
                  - type: mrkdwn
                    text: "<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|:git-merged: Pull Request>"
                  - type: mrkdwn
                    text: "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|:runner: Scan Details>"
